FROM docker.io/opensuse/tumbleweed:latest

ENV container=podman

RUN zypper --non-interactive refresh \
    && zypper --non-interactive install --no-recommends \
        ca-certificates curl dbus-1 e2fsprogs ffmpeg-7 iproute2 libicu libjemalloc2 \
        libstdc++6 mozilla-nss-tools procps python3 systemd util-linux \
        util-linux-systemd \
    && zypper clean --all \
    && systemctl mask \
        console-getty.service getty@.service systemd-logind.service \
        systemd-remount-fs.service

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
